version: '3.8'

services:
  # MySQL服务
  mysql:
    image: mysql:8.0
    container_name: computerstore-mysql
    restart: always
    environment:
      MYSQL_DATABASE: computer_store
      MYSQL_ROOT_PASSWORD: 062512
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p062512"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE  # 解决MySQL 8可能的性能问题

  # 应用服务
  app:
    build: .
    container_name: computerstore-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/computer_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 062512

volumes:
  mysql-data: 